### ISSUE TITLE
Migrate from suds to zeep

### ISSUE THREAD

**Issue by Letme** [melexis/sphinx-coverity-extension#1]
Suds has its problems, so they created zeep (http://docs.python-zeep.org/en/master/). Make sure we migrate as soon as possible to avoid any problems by suds (which is not maintained).

**Comment by Letme** [comment]
There is suds-py3 nowdays for python 3.

**Comment by JasperCraeghs** [comment]
Using Coverity REST API since #74 , which is more modern and faster. Closing this issue.
