### ISSUE TITLE
Parse comments for custom pattern to create a hyperlink

### ISSUE THREAD

**Issue by Letme** [melexis/sphinx-coverity-extension#27]
When we link Coverity extension with Traceability extension that means we describe our Coverity deviations with items from traceability extension. That means comments to Coverity issues include traceability item ID which should be linked to that item (ref in docnode). Also all hyperlinks should be made links.

That means when you have traceability item in something.rst:

```
.. item:: DEVIATION-SOMETHING We deviate from Something rule
    
    We want to deviate from this rule, because usage in X does not correspond to our style
    of work and we think something else is a lot better.
```
With comment in Coverity Connect:
```
Triagged because DEVIATION-SOMETHING
```

Then final for example html output in the Coverity table under comment column should be:
```
Tiagged because <a href=something.html#deviation-something>DEVIATION-SOMETHING</a>
```

The link should be done in docnode so that also other builders can make a valid link.

You define the regex for traceability item id in the `coverity.config` in `conf.py` (or we can make default all caps with `-` and `_` separator as a link.)

**Comment by JasperCraeghs** [comment]
closed by #28
