### ISSUE TITLE
Provide option for column file:linenum

### ISSUE THREAD

**Issue by Letme** [melexis/sphinx-coverity-extension#34]
Provide new column where you would print in format of `file:linenum` of the defect. This will be useful when someone does not have access to CID, but still wants to read/compare report with the source code (manually).

That means instead of link to CID, print the file path and line number. Since this will be long and to enable some context, we could also maybe use the format of the Link towards gitlab (there linenum is in format `filename.c#L140`.

**Comment by JasperCraeghs** [comment]
Is there a way to get the line number from the defect object?

**Comment by Letme** [comment]
I do not know, if it is soap response (in `defect.xml` I dont see it, only the `functionName`). You should investigate.

**Comment by Letme** [comment]
Closed by #35
