### ISSUE TITLE
Provide ability to re-link the TRACEABILITY_ITEM_ID

### ISSUE THREAD

**Issue by Letme** [melexis/sphinx-coverity-extension#62]
There are many projects sharing the Triage store, but so far deviations described in traceability have different `TRACEABILITY_ITEM_ID`. That means we need to provide capabilities to relink existing `TRACEABILITY_ITEM_ID` to `TRACEABILITY_NEWITEM_ID`. Similar to what Traceability extension has with item-relink directive (https://melexis.github.io/sphinx-traceability-extension/usage.html#changing-targets-or-removing-relationships), just that here the type is not important.

**Comment by JasperCraeghs** [comment]
Do you want to select item IDs by specifying a regular expression (more flexible) or just a simple string (easier and more performant)?

**Comment by Letme** [comment]
it needs to be `source_string : target_string` pair, where if we have a match for `source_string`, we need to replace it by `target_string`. Should be as simple as that, second option I would also like to consider is that we would make sure `item-relink` directive from Sphinx Traceability extension is adding the same source:target search&replace pairs into this coverity extension list. That would be cool.
